Update boilerplate versions
eoscostarica/backend-boilerplate pull request #21
Opened 2022-08-08 14:21 UTC by hanakoori01

### What does this PR do?

- Resolve #19 

### Steps to test

1. Run `make run`

2022-08-08 17:44 UTC, leisterfrancisco requested changes

2022-08-08 17:44 UTC, leisterfrancisco commented on yarn.lock
> +
run `yarn` inside of the hapi folder to create the final `yarn.lock` file

2022-08-08 18:24 UTC, leisterfrancisco requested changes

2022-08-08 18:24 UTC, leisterfrancisco commented on hapi/package.json
> +    "husky": "^8.0.1",
Husky requires a new structure, please, check the [official documentation](https://typicode.github.io/husky/#/?id=install).

2022-08-11 02:07 UTC, leisterfrancisco requested changes

2022-08-11 02:07 UTC, leisterfrancisco commented on hapi/package.json
> +    "lint": "lint-staged",
remove this, new husky version handles it different

2022-08-11 02:11 UTC, leisterfrancisco commented
@hanakoori01 please update Hasura image to the latest version to support `linux/arm64/v8`, more [here](https://hub.docker.com/layers/graphql-engine/hasura/graphql-engine/v2.11.0-beta.1.cli-migrations-v3/images/sha256-e1ac97c034299853c84928c2abd770758824308a7dcd1f48ce64f31e29527ef6?context=explore)

2022-08-12 00:44 UTC, xavier506 requested changes
check hasura version change in docker-compose

2022-08-12 00:44 UTC, xavier506 commented on hasura/Dockerfile
> +FROM hasura/graphql-engine:v2.11.0-beta.1.cli-migrations-v3
this version change also needs to happen in docker-compose.yml

2022-08-12 03:01 UTC, xavier506 requested changes
lets update docker compose to version 3.8
currently in `docker-compose.yml`
```version: "3.6"```

2022-08-16 13:55 UTC, leisterfrancisco requested changes

2022-08-16 13:55 UTC, leisterfrancisco commented on hapi/package.json
>    "license": "MIT",
let's add this:

```
"lint-staged": {
    "*.js": [
      "eslint",
      "prettier --write"
    ]
  }
```

2022-08-16 17:57 UTC, leisterfrancisco approved these changes

2022-08-16 18:19 UTC, xavier506 approved these changes
LGTM

2022-08-17 14:44 UTC, xavier506 approved these changes
LGTM

2022-08-17 14:44 UTC, merged